site_name: Complib Help
site_url: https://help.complib.org
nav:
  - Introduction: index.md
  - Core concepts: concepts.md
  - 'User Accounts':
    - Signing up for an account: user/account_signup.md
    - Resetting your password: user/reset_password.md
    - User profile and settings: user/user_profile.md
  - 'Compositions':
    - Composition pages: compositions/overview.md
    - Customising composition layouts: compositions/layout_options.md
    - Composition properties: compositions/composition_properties.md
  - 'Adding & Editing Compositions':
    - "Adding compositions: overview": compositions/adding_compositions_overview.md
    - The General tab: compositions/adding_compositions_tabs_general.md
    - The Methods tab: compositions/adding_compositions_tabs_methods.md
    - The Calls tab: compositions/adding_compositions_tabs_calls.md
    - The Calling tab: compositions/adding_compositions_tabs_calling.md
    - Calling positions: compositions/calling_positions.md
  - 'Methods':
    - Method pages: methods/overview.md
    - Customising the blue line: methods/blueline_options.md
    - Method properties: methods/method_properties.md
    - Adding methods: methods/adding_methods.md
    - Place notation: methods/place_notation.md
    - Using the method designer: methods/method_designer.md
  - 'Collections':
    - What are collections?: collections/overview.md
    - Adding collections: collections/adding_collections.md 
  - 'Searching Complib':
    - Quick search: search/quick_search.md
    - Method search: search/method_search.md
    - Composition search: search/composition_search.md
    - Collection search: search/collection_search.md
    - Extended search: search/extended_search.md
  - 'Advanced Topics':
    - Extensions: advanced/extensions.md
    #- False coursehead (FCH) groups: advanced/fch_groups.md
    - Leadhead codes: advanced/leadhead_codes.md
    - Music schemes: advanced/music_schemes.md
    - Row parity: advanced/row_parity.md

theme: readthedocs
markdown_extensions:
  - admonition
  - def_list
  - attr_list
  - pymdownx.details
